-- Generated by scripts/build-data-packages.ps1. Do not edit an applied version.
-- All statements are PostgreSQL SQL; psql must be run with ON_ERROR_STOP=1.
BEGIN;
SET LOCAL TIME ZONE 'UTC';
SET LOCAL search_path TO public;
SELECT pg_advisory_xact_lock(73481, 1);
CREATE TABLE IF NOT EXISTS schema_migrations (
    version integer PRIMARY KEY,
    description text NOT NULL,
    checksum text NOT NULL CHECK (length(checksum) = 64),
    applied_at timestamptz NOT NULL DEFAULT now()
);
DO $migration_runner$
BEGIN
    IF EXISTS (SELECT 1 FROM schema_migrations WHERE version = 1) THEN
        IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = 1 AND checksum = '86e22dc2db2e275620ffdd60427e032c0f2602df685cf442fa3be50b3f4ae1f7') THEN
            RAISE EXCEPTION 'V001 checksum mismatch: create a new migration version';
        END IF;
        RAISE NOTICE 'V001 already applied; skipped';
    ELSE
        EXECUTE $schema_payload$
-- Source: 010_organization.sql
-- 组织和权限。公司组合外键防止跨租户引用；应用仍须逐次鉴权。
CREATE TABLE companies (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL CHECK (btrim(name) <> ''),
    timezone text NOT NULL DEFAULT 'Asia/Shanghai',
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE departments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id),
    name text NOT NULL CHECK (btrim(name) <> ''),
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, id), UNIQUE (company_id, name)
);
CREATE TABLE teams (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id),
    department_id uuid NOT NULL,
    name text NOT NULL CHECK (btrim(name) <> ''),
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, id), UNIQUE (company_id, department_id, id),
    UNIQUE (company_id, department_id, name),
    FOREIGN KEY (company_id, department_id) REFERENCES departments(company_id, id)
);
CREATE TABLE users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id),
    username text NOT NULL CHECK (btrim(username) <> ''),
    password_hash text NOT NULL CHECK (btrim(password_hash) <> ''),
    phone text NOT NULL UNIQUE CHECK (phone ~ '^\+?[0-9]{7,15}$'),
    display_name text NOT NULL CHECK (btrim(display_name) <> ''),
    department_id uuid,
    team_id uuid,
    membership_status text NOT NULL DEFAULT 'pending'
        CHECK (membership_status IN ('pending', 'active', 'disabled')),
    must_change_password boolean NOT NULL DEFAULT false,
    session_version integer NOT NULL DEFAULT 1 CHECK (session_version > 0),
    avatar_url text, introduction text,
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (team_id IS NULL OR department_id IS NOT NULL),
    UNIQUE (company_id, id), UNIQUE (company_id, username),
    FOREIGN KEY (company_id, department_id) REFERENCES departments(company_id, id),
    FOREIGN KEY (company_id, department_id, team_id) REFERENCES teams(company_id, department_id, id)
);
CREATE TABLE roles (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id),
    code text NOT NULL CHECK (code IN ('admin', 'founder', 'department_head', 'team_lead', 'employee')),
    name text NOT NULL,
    data_scope text NOT NULL CHECK (data_scope IN ('self', 'team', 'department', 'company')),
    UNIQUE (company_id, id), UNIQUE (company_id, code)
);
CREATE TABLE permissions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id),
    code text NOT NULL, name text NOT NULL,
    UNIQUE (company_id, id), UNIQUE (company_id, code)
);
CREATE TABLE role_permissions (
    company_id uuid NOT NULL REFERENCES companies(id),
    role_id uuid NOT NULL, permission_id uuid NOT NULL,
    PRIMARY KEY (company_id, role_id, permission_id),
    FOREIGN KEY (company_id, role_id) REFERENCES roles(company_id, id),
    FOREIGN KEY (company_id, permission_id) REFERENCES permissions(company_id, id)
);
CREATE TABLE user_roles (
    company_id uuid NOT NULL REFERENCES companies(id),
    user_id uuid NOT NULL, role_id uuid NOT NULL, granted_by uuid,
    granted_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (company_id, user_id, role_id),
    FOREIGN KEY (company_id, user_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, role_id) REFERENCES roles(company_id, id),
    FOREIGN KEY (company_id, granted_by) REFERENCES users(company_id, id)
);
CREATE TABLE reporting_relations (
    company_id uuid NOT NULL REFERENCES companies(id),
    employee_id uuid NOT NULL, manager_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (company_id, employee_id),
    CHECK (employee_id <> manager_id),
    FOREIGN KEY (company_id, employee_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, manager_id) REFERENCES users(company_id, id)
);

CREATE FUNCTION prevent_reporting_cycle() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    -- 公司行锁串行化关系修改，防止并发形成循环。
    PERFORM 1 FROM companies WHERE id = NEW.company_id FOR UPDATE;
    IF EXISTS (
        WITH RECURSIVE ancestors(id) AS (
            SELECT NEW.manager_id
            UNION
            SELECT r.manager_id FROM reporting_relations r JOIN ancestors a ON r.employee_id = a.id
            WHERE r.company_id = NEW.company_id
        ) SELECT 1 FROM ancestors WHERE id = NEW.employee_id
    ) THEN
        RAISE EXCEPTION 'reporting relation cycle' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER reporting_cycle_guard BEFORE INSERT OR UPDATE ON reporting_relations
    FOR EACH ROW EXECUTE FUNCTION prevent_reporting_cycle();

CREATE FUNCTION assign_default_employee_role() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE employee_role uuid;
BEGIN
    SELECT id INTO employee_role FROM roles WHERE company_id = NEW.company_id AND code = 'employee';
    IF employee_role IS NULL THEN
        RAISE EXCEPTION 'company employee role must be initialized first';
    END IF;
    INSERT INTO user_roles(company_id, user_id, role_id) VALUES (NEW.company_id, NEW.id, employee_role);
    RETURN NEW;
END $$;
CREATE TRIGGER user_default_employee AFTER INSERT ON users
    FOR EACH ROW EXECUTE FUNCTION assign_default_employee_role();

-- Source: 020_work.sql
-- 任务、展示项和日报。派发页面不读取或呈现完成情况列。
CREATE TABLE tasks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id),
    title text NOT NULL CHECK (btrim(title) <> ''),
    group_name text NOT NULL DEFAULT '未分组',
    content text NOT NULL DEFAULT '',
    due_at timestamptz NOT NULL,
    urgency text NOT NULL DEFAULT 'normal' CHECK (urgency IN ('urgent', 'normal', 'low')),
    progress_note text NOT NULL DEFAULT '',
    created_by uuid NOT NULL,
    primary_assignee_id uuid NOT NULL,
    parent_task_id uuid,
    idempotency_key text NOT NULL CHECK (btrim(idempotency_key) <> ''),
    attachments jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(attachments) = 'array'),
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    archived_at timestamptz,
    UNIQUE (company_id, id), UNIQUE (company_id, created_by, idempotency_key),
    CHECK (parent_task_id IS NULL OR parent_task_id <> id),
    FOREIGN KEY (company_id, created_by) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, primary_assignee_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, parent_task_id) REFERENCES tasks(company_id, id)
);
CREATE TABLE task_assignees (
    company_id uuid NOT NULL REFERENCES companies(id), task_id uuid NOT NULL,
    user_id uuid NOT NULL,
    assigned_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (company_id, task_id, user_id),
    FOREIGN KEY (company_id, task_id) REFERENCES tasks(company_id, id),
    FOREIGN KEY (company_id, user_id) REFERENCES users(company_id, id)
);
COMMENT ON TABLE task_assignees IS '可选协作者；唯一主负责人在 tasks.primary_assignee_id';
CREATE TABLE task_events (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), task_id uuid NOT NULL,
    actor_id uuid NOT NULL,
    event_type text NOT NULL CHECK (event_type IN
        ('dispatched', 'received', 'feedback', 'accepted', 'reassigned', 'withdrawn', 'deadline_changed', 'archived')),
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, id),
    FOREIGN KEY (company_id, task_id) REFERENCES tasks(company_id, id),
    FOREIGN KEY (company_id, actor_id) REFERENCES users(company_id, id)
);
CREATE TABLE dashboard_items (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id),
    owner_id uuid,
    audience text NOT NULL CHECK (audience IN ('company', 'department', 'team', 'personal')),
    department_id uuid, team_id uuid, task_id uuid,
    item_type text NOT NULL CHECK (item_type IN ('highlight', 'task')),
    title text NOT NULL CHECK (btrim(title) <> ''), content text NOT NULL DEFAULT '',
    pinned_position smallint CHECK (pinned_position BETWEEN 1 AND 10),
    created_by uuid NOT NULL,
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(), archived_at timestamptz,
    CHECK ((audience = 'company' AND owner_id IS NULL AND department_id IS NULL AND team_id IS NULL)
        OR (audience = 'department' AND department_id IS NOT NULL AND team_id IS NULL AND owner_id IS NULL)
        OR (audience = 'team' AND team_id IS NOT NULL AND department_id IS NOT NULL AND owner_id IS NULL)
        OR (audience = 'personal' AND owner_id IS NOT NULL AND department_id IS NULL AND team_id IS NULL)),
    CHECK ((item_type = 'task') = (task_id IS NOT NULL)),
    UNIQUE (company_id, id),
    FOREIGN KEY (company_id, owner_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, created_by) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, department_id) REFERENCES departments(company_id, id),
    FOREIGN KEY (company_id, department_id, team_id) REFERENCES teams(company_id, department_id, id),
    FOREIGN KEY (company_id, task_id) REFERENCES tasks(company_id, id)
);
CREATE UNIQUE INDEX dashboard_pin_unique ON dashboard_items
    (company_id, audience, owner_id, department_id, team_id, item_type, pinned_position) NULLS NOT DISTINCT
    WHERE archived_at IS NULL AND pinned_position IS NOT NULL;
CREATE TABLE private_notes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), owner_id uuid NOT NULL,
    dashboard_item_id uuid, task_id uuid,
    content text NOT NULL DEFAULT '',
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(dashboard_item_id, task_id) = 1),
    UNIQUE (company_id, id),
    FOREIGN KEY (company_id, owner_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, dashboard_item_id) REFERENCES dashboard_items(company_id, id),
    FOREIGN KEY (company_id, task_id) REFERENCES tasks(company_id, id)
);
CREATE UNIQUE INDEX private_note_item_unique ON private_notes(company_id, owner_id, dashboard_item_id)
    WHERE dashboard_item_id IS NOT NULL;
CREATE UNIQUE INDEX private_note_task_unique ON private_notes(company_id, owner_id, task_id)
    WHERE task_id IS NOT NULL;
CREATE TABLE daily_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), user_id uuid NOT NULL,
    business_date date NOT NULL,
    today_work text NOT NULL DEFAULT '', blockers text NOT NULL DEFAULT '', tomorrow_plan text NOT NULL DEFAULT '',
    work_hours numeric(4,2) CHECK (work_hours BETWEEN 0 AND 24),
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted')),
    submitted_at timestamptz,
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((status = 'submitted') = (submitted_at IS NOT NULL)),
    UNIQUE (company_id, id), UNIQUE (company_id, user_id, business_date),
    FOREIGN KEY (company_id, user_id) REFERENCES users(company_id, id)
);
CREATE TABLE log_tasks (
    company_id uuid NOT NULL REFERENCES companies(id), log_id uuid NOT NULL, task_id uuid NOT NULL,
    PRIMARY KEY (company_id, log_id, task_id),
    FOREIGN KEY (company_id, log_id) REFERENCES daily_logs(company_id, id),
    FOREIGN KEY (company_id, task_id) REFERENCES tasks(company_id, id)
);
CREATE TABLE log_versions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), log_id uuid NOT NULL,
    version integer NOT NULL CHECK (version > 0),
    content jsonb NOT NULL CHECK (jsonb_typeof(content) = 'object'),
    edited_by uuid NOT NULL, reason text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, id), UNIQUE (company_id, log_id, version),
    FOREIGN KEY (company_id, log_id) REFERENCES daily_logs(company_id, id),
    FOREIGN KEY (company_id, edited_by) REFERENCES users(company_id, id)
);
CREATE TABLE log_reads (
    company_id uuid NOT NULL REFERENCES companies(id), log_id uuid NOT NULL,
    reader_id uuid NOT NULL, read_at timestamptz NOT NULL DEFAULT now(), comment text NOT NULL DEFAULT '',
    PRIMARY KEY (company_id, log_id, reader_id),
    FOREIGN KEY (company_id, log_id) REFERENCES daily_logs(company_id, id),
    FOREIGN KEY (company_id, reader_id) REFERENCES users(company_id, id)
);

-- Source: 030_review_messages_ai.sql
-- 复核保存候选版本；审核生效、版本比较与范围由后续服务端事务负责。
CREATE TABLE review_requests (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), applicant_id uuid NOT NULL,
    object_type text NOT NULL CHECK (object_type IN ('organization', 'role', 'dashboard_item', 'task', 'daily_log')),
    object_id uuid NOT NULL,
    base_version integer NOT NULL CHECK (base_version >= 0),
    before_value jsonb NOT NULL DEFAULT '{}'::jsonb,
    candidate_value jsonb NOT NULL CHECK (jsonb_typeof(candidate_value) = 'object'),
    reason text NOT NULL CHECK (btrim(reason) <> ''),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(), decided_at timestamptz,
    UNIQUE (company_id, id), UNIQUE (company_id, id, applicant_id),
    FOREIGN KEY (company_id, applicant_id) REFERENCES users(company_id, id)
);
CREATE TABLE review_steps (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), review_request_id uuid NOT NULL,
    applicant_id uuid NOT NULL, reviewer_id uuid NOT NULL,
    step_order smallint NOT NULL CHECK (step_order > 0),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'skipped')),
    comment text NOT NULL DEFAULT '', decided_at timestamptz,
    CHECK (reviewer_id <> applicant_id),
    CHECK (status <> 'rejected' OR btrim(comment) <> ''),
    CHECK ((status IN ('approved', 'rejected')) = (decided_at IS NOT NULL)),
    UNIQUE (company_id, id), UNIQUE (company_id, review_request_id, step_order),
    FOREIGN KEY (company_id, review_request_id, applicant_id) REFERENCES review_requests(company_id, id, applicant_id),
    FOREIGN KEY (company_id, reviewer_id) REFERENCES users(company_id, id)
);
CREATE TABLE audit_records (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), actor_id uuid,
    action text NOT NULL, object_type text NOT NULL, object_id uuid,
    before_value jsonb, after_value jsonb,
    reason text NOT NULL, review_request_id uuid, trace_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, id),
    FOREIGN KEY (company_id, actor_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, review_request_id) REFERENCES review_requests(company_id, id)
);
CREATE TABLE outbox_events (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id),
    event_type text NOT NULL, aggregate_type text NOT NULL, aggregate_id uuid NOT NULL,
    payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object'),
    dedup_key text NOT NULL,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    available_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz,
    last_error text, created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, id), UNIQUE (company_id, dedup_key)
);
CREATE TABLE notifications (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), recipient_id uuid NOT NULL,
    notification_type text NOT NULL CHECK (notification_type IN
        ('task_dispatch', 'task_deadline', 'review_pending', 'review_result', 'log_submitted', 'task_event')),
    title text NOT NULL, body text NOT NULL DEFAULT '', target_type text NOT NULL, target_id uuid NOT NULL,
    outbox_event_id uuid, dedup_key text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(), read_at timestamptz,
    UNIQUE (company_id, id), UNIQUE (company_id, recipient_id, dedup_key),
    FOREIGN KEY (company_id, recipient_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, outbox_event_id) REFERENCES outbox_events(company_id, id)
);
CREATE TABLE ai_jobs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), requested_by uuid NOT NULL,
    job_type text NOT NULL CHECK (job_type IN ('daily_summary', 'weekly_summary', 'map_extract', 'risk_explain', 'task_draft')),
    status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    model text NOT NULL, input jsonb NOT NULL, output jsonb,
    sources jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(sources) = 'array'),
    input_tokens integer NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
    output_tokens integer NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
    cost numeric(14,6) NOT NULL DEFAULT 0 CHECK (cost >= 0),
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    error_code text, error_message text, cancelled_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, finished_at timestamptz,
    UNIQUE (company_id, id),
    FOREIGN KEY (company_id, requested_by) REFERENCES users(company_id, id)
);
COMMENT ON TABLE ai_jobs IS '建议草稿及来源；不得保存 DeepSeek 密钥、手机号、密码或私人备注';
CREATE TABLE ai_map_nodes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), owner_id uuid NOT NULL, ai_job_id uuid,
    node_type text NOT NULL CHECK (node_type IN ('goal', 'task', 'highlight', 'log', 'blocker', 'risk', 'action')),
    title text NOT NULL, content text NOT NULL DEFAULT '',
    task_id uuid, log_id uuid, dashboard_item_id uuid,
    sources jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(sources) = 'array'),
    is_suggestion boolean NOT NULL DEFAULT true,
    position_x numeric NOT NULL DEFAULT 0, position_y numeric NOT NULL DEFAULT 0,
    version integer NOT NULL DEFAULT 1 CHECK (version > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, id), UNIQUE (company_id, owner_id, id),
    FOREIGN KEY (company_id, owner_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, ai_job_id) REFERENCES ai_jobs(company_id, id),
    FOREIGN KEY (company_id, task_id) REFERENCES tasks(company_id, id),
    FOREIGN KEY (company_id, log_id) REFERENCES daily_logs(company_id, id),
    FOREIGN KEY (company_id, dashboard_item_id) REFERENCES dashboard_items(company_id, id)
);
CREATE TABLE ai_map_edges (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id uuid NOT NULL REFERENCES companies(id), owner_id uuid NOT NULL,
    source_node_id uuid NOT NULL, target_node_id uuid NOT NULL,
    edge_type text NOT NULL CHECK (edge_type IN ('depends_on', 'related_to', 'blocks', 'supports')),
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (source_node_id <> target_node_id),
    UNIQUE (company_id, id), UNIQUE (company_id, owner_id, source_node_id, target_node_id, edge_type),
    FOREIGN KEY (company_id, owner_id) REFERENCES users(company_id, id),
    FOREIGN KEY (company_id, owner_id, source_node_id) REFERENCES ai_map_nodes(company_id, owner_id, id),
    FOREIGN KEY (company_id, owner_id, target_node_id) REFERENCES ai_map_nodes(company_id, owner_id, id)
);

-- Source: 040_indexes_seed.sql
CREATE INDEX users_department_idx ON users(company_id, department_id, membership_status);
CREATE INDEX users_team_idx ON users(company_id, team_id, membership_status);
CREATE INDEX reporting_manager_idx ON reporting_relations(company_id, manager_id);
CREATE INDEX tasks_assignee_due_idx ON tasks(company_id, primary_assignee_id, due_at) WHERE archived_at IS NULL;
CREATE INDEX tasks_creator_idx ON tasks(company_id, created_by, created_at DESC);
CREATE INDEX task_events_timeline_idx ON task_events(company_id, task_id, created_at, id);
CREATE INDEX task_assignees_user_idx ON task_assignees(company_id, user_id);
CREATE INDEX daily_logs_range_idx ON daily_logs(company_id, business_date, user_id) WHERE status = 'submitted';
CREATE INDEX reviews_pending_idx ON review_requests(company_id, created_at) WHERE status = 'pending';
CREATE INDEX review_steps_reviewer_idx ON review_steps(company_id, reviewer_id) WHERE status = 'pending';
CREATE INDEX audit_records_time_idx ON audit_records(company_id, created_at DESC);
CREATE INDEX notifications_unread_idx ON notifications(company_id, recipient_id, created_at DESC) WHERE read_at IS NULL;
CREATE INDEX outbox_pending_idx ON outbox_events(available_at, created_at) WHERE published_at IS NULL;
CREATE INDEX ai_jobs_owner_idx ON ai_jobs(company_id, requested_by, created_at DESC);
CREATE INDEX ai_jobs_queue_idx ON ai_jobs(created_at) WHERE status = 'queued';
CREATE INDEX ai_map_nodes_owner_idx ON ai_map_nodes(company_id, owner_id);

-- 固定引导公司 ID；仅基础组织，不创建默认密码或演示业务数据。
INSERT INTO companies(id, name) VALUES ('00000000-0000-0000-0000-000000000001', '企业协作');
INSERT INTO departments(company_id, name)
SELECT '00000000-0000-0000-0000-000000000001'::uuid, name
FROM (VALUES ('产品部'), ('市场部'), ('技术部')) AS defaults(name);
INSERT INTO roles(company_id, code, name, data_scope)
SELECT '00000000-0000-0000-0000-000000000001'::uuid, code, name, scope
FROM (VALUES ('admin', '管理员', 'company'), ('founder', '创始人', 'company'),
    ('department_head', '部门老总', 'department'), ('team_lead', '团队长', 'team'),
    ('employee', '员工', 'self')) AS defaults(code, name, scope);
INSERT INTO permissions(company_id, code, name)
SELECT '00000000-0000-0000-0000-000000000001'::uuid, code, name
FROM (VALUES ('organization.manage', '组织配置'), ('role.manage', '角色授权'),
    ('task.dispatch', '任务派发'), ('task.feedback', '任务反馈'),
    ('log.write', '本人日志'), ('log.read_subordinates', '下属日志'),
    ('dashboard.publish', '公司内容发布'), ('review.decide', '独立复核'),
    ('analytics.read', '范围统计'), ('ai.use', 'AI建议')) AS defaults(code, name);
INSERT INTO role_permissions(company_id, role_id, permission_id)
SELECT r.company_id, r.id, p.id FROM roles r JOIN permissions p ON p.company_id = r.company_id
WHERE r.code = 'admin'
    OR (p.code IN ('task.feedback', 'log.write', 'ai.use'))
    OR (r.code IN ('founder', 'department_head', 'team_lead') AND p.code IN
        ('task.dispatch', 'log.read_subordinates', 'dashboard.publish', 'review.decide', 'analytics.read'));
INSERT INTO audit_records(company_id, action, object_type, object_id, reason, after_value)
VALUES ('00000000-0000-0000-0000-000000000001', 'bootstrap.schema', 'company',
    '00000000-0000-0000-0000-000000000001', 'V001 数据基础初始化；管理员由后续服务端安全初始化',
    '{"departments":3,"roles":5,"default_admin_created":false}'::jsonb);

$schema_payload$;
        INSERT INTO schema_migrations(version, description, checksum)
        VALUES (1, 'Initial collaboration schema', '86e22dc2db2e275620ffdd60427e032c0f2602df685cf442fa3be50b3f4ae1f7');
        RAISE NOTICE 'V001 applied';
    END IF;
END
$migration_runner$;
COMMIT;
