-- 服务层先鉴权，数据库再阻止跨公司关联；迁移保持追加式。
ALTER TABLE departments ADD UNIQUE (company_id,id);
ALTER TABLE teams ADD UNIQUE (company_id,id,department_id);
ALTER TABLE teams ADD FOREIGN KEY (company_id,department_id) REFERENCES departments(company_id,id);
ALTER TABLE users ADD UNIQUE (company_id,id);
ALTER TABLE users ADD FOREIGN KEY (company_id,department_id) REFERENCES departments(company_id,id);
ALTER TABLE users ADD FOREIGN KEY (company_id,team_id,department_id) REFERENCES teams(company_id,id,department_id);
ALTER TABLE users ADD CHECK (team_id IS NULL OR department_id IS NOT NULL);
ALTER TABLE reporting_relations ADD FOREIGN KEY (company_id,employee_id) REFERENCES users(company_id,id);
ALTER TABLE reporting_relations ADD FOREIGN KEY (company_id,manager_id) REFERENCES users(company_id,id);
ALTER TABLE dashboard_items ADD FOREIGN KEY (company_id,owner_id) REFERENCES users(company_id,id);
ALTER TABLE private_notes ADD FOREIGN KEY (company_id,owner_id) REFERENCES users(company_id,id);
ALTER TABLE tasks ADD UNIQUE (company_id,id);
ALTER TABLE tasks ADD FOREIGN KEY (company_id,owner_id) REFERENCES users(company_id,id);
ALTER TABLE tasks ADD FOREIGN KEY (company_id,issuer_id) REFERENCES users(company_id,id);
ALTER TABLE tasks ADD CHECK (phase IN ('DISPATCHED','RECEIVED','FEEDBACK','ACCEPTED','ARCHIVED','WITHDRAWN'));
ALTER TABLE task_assignees ADD COLUMN company_id text;
UPDATE task_assignees a SET company_id=t.company_id FROM tasks t WHERE a.task_id=t.id;
ALTER TABLE task_assignees ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE task_assignees ADD FOREIGN KEY (company_id,task_id) REFERENCES tasks(company_id,id);
ALTER TABLE task_assignees ADD FOREIGN KEY (company_id,user_id) REFERENCES users(company_id,id);
ALTER TABLE task_assignees ADD CHECK (kind IN ('PRIMARY','COLLABORATOR'));
CREATE UNIQUE INDEX task_one_primary ON task_assignees(task_id) WHERE kind='PRIMARY';
ALTER TABLE task_events ADD FOREIGN KEY (company_id,task_id) REFERENCES tasks(company_id,id);
ALTER TABLE task_events ADD FOREIGN KEY (company_id,actor_id) REFERENCES users(company_id,id);
ALTER TABLE daily_logs ADD UNIQUE (company_id,id);
ALTER TABLE daily_logs ADD FOREIGN KEY (company_id,owner_id) REFERENCES users(company_id,id);
ALTER TABLE log_versions ADD FOREIGN KEY (company_id,log_id) REFERENCES daily_logs(company_id,id);
ALTER TABLE log_comments ADD FOREIGN KEY (company_id,log_id) REFERENCES daily_logs(company_id,id);
ALTER TABLE log_comments ADD FOREIGN KEY (company_id,actor_id) REFERENCES users(company_id,id);
ALTER TABLE review_requests ADD UNIQUE (company_id,id);
ALTER TABLE review_requests ADD FOREIGN KEY (company_id,applicant_id) REFERENCES users(company_id,id);
ALTER TABLE review_requests ADD CHECK (status IN ('PENDING','APPROVED','REJECTED'));
ALTER TABLE review_steps ADD COLUMN company_id text;
UPDATE review_steps s SET company_id=r.company_id FROM review_requests r WHERE s.request_id=r.id;
ALTER TABLE review_steps ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE review_steps ADD FOREIGN KEY (company_id,request_id) REFERENCES review_requests(company_id,id);
ALTER TABLE review_steps ADD FOREIGN KEY (company_id,reviewer_id) REFERENCES users(company_id,id);
ALTER TABLE review_steps ADD CHECK (state IN ('PENDING','APPROVED','REJECTED'));
ALTER TABLE audit_records ADD FOREIGN KEY (company_id,actor_id) REFERENCES users(company_id,id);
ALTER TABLE outbox_events ADD UNIQUE (company_id,id);
ALTER TABLE outbox_events ADD FOREIGN KEY (company_id,recipient_id) REFERENCES users(company_id,id);
ALTER TABLE notifications ADD FOREIGN KEY (company_id,id) REFERENCES outbox_events(company_id,id);
ALTER TABLE notifications ADD FOREIGN KEY (company_id,recipient_id) REFERENCES users(company_id,id);
ALTER TABLE idempotency_keys ADD FOREIGN KEY (company_id,actor_id) REFERENCES users(company_id,id);
ALTER TABLE idempotency_keys ADD FOREIGN KEY (company_id,task_id) REFERENCES tasks(company_id,id);
ALTER TABLE attachments ADD FOREIGN KEY (company_id,owner_id) REFERENCES users(company_id,id);
ALTER TABLE attachments ADD FOREIGN KEY (company_id,task_id) REFERENCES tasks(company_id,id);
ALTER TABLE ai_jobs ADD UNIQUE (company_id,id);
ALTER TABLE ai_jobs ADD FOREIGN KEY (company_id,owner_id) REFERENCES users(company_id,id);
ALTER TABLE ai_jobs ADD CHECK (state IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED'));
ALTER TABLE ai_map_nodes ADD UNIQUE (company_id,id,owner_id);
ALTER TABLE ai_map_nodes ADD FOREIGN KEY (company_id,owner_id) REFERENCES users(company_id,id);
ALTER TABLE ai_map_nodes ADD FOREIGN KEY (company_id,job_id) REFERENCES ai_jobs(company_id,id);
ALTER TABLE ai_map_edges ADD FOREIGN KEY (company_id,source_id,owner_id) REFERENCES ai_map_nodes(company_id,id,owner_id);
ALTER TABLE ai_map_edges ADD FOREIGN KEY (company_id,target_id,owner_id) REFERENCES ai_map_nodes(company_id,id,owner_id);
ALTER TABLE ai_map_edges ADD CHECK (source_id<>target_id);
CREATE INDEX tasks_issuer ON tasks(company_id,issuer_id);
CREATE INDEX task_participants ON task_assignees(user_id,task_id);
CREATE INDEX event_type ON task_events(task_id,type,created_at);
CREATE INDEX review_assignee ON review_steps(reviewer_id,request_id);
CREATE INDEX ai_queue ON ai_jobs(created_at) WHERE state='QUEUED';
