param([string]$OutputDirectory)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$deploy = Join-Path $root 'deploy'
if (!$OutputDirectory) { $OutputDirectory = Join-Path $deploy 'dist' }
$utf8 = New-Object System.Text.UTF8Encoding($false)
$postgres = Join-Path $deploy 'postgresql'
$sources = @(Get-ChildItem (Join-Path $postgres 'sql') -Filter '*.sql' | Sort-Object Name)
if ($sources.Count -eq 0) { throw 'No SQL sources found.' }
$body = ($sources | ForEach-Object {
    "-- Source: $($_.Name)`n" + [IO.File]::ReadAllText($_.FullName).Replace("`r`n", "`n").TrimEnd() + "`n"
}) -join "`n"
if ($body.Contains('$schema_payload$')) { throw 'Reserved migration delimiter found in source.' }
$sha = [Security.Cryptography.SHA256]::Create()
try { $checksum = ([BitConverter]::ToString($sha.ComputeHash($utf8.GetBytes($body)))).Replace('-', '').ToLowerInvariant() }
finally { $sha.Dispose() }
$template = @'
-- Generated by scripts/build-data-packages.ps1. Do not edit an applied version.
-- All statements are PostgreSQL SQL; psql must be run with ON_ERROR_STOP=1.
BEGIN;
SET LOCAL TIME ZONE 'UTC';
SET LOCAL search_path TO public;
SELECT pg_advisory_xact_lock(73481, 1);
CREATE TABLE IF NOT EXISTS schema_migrations (
    version integer PRIMARY KEY,
    description text NOT NULL,
    checksum text NOT NULL CHECK (length(checksum) = 64),
    applied_at timestamptz NOT NULL DEFAULT now()
);
DO $migration_runner$
BEGIN
    IF EXISTS (SELECT 1 FROM schema_migrations WHERE version = 1) THEN
        IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = 1 AND checksum = '__CHECKSUM__') THEN
            RAISE EXCEPTION 'V001 checksum mismatch: create a new migration version';
        END IF;
        RAISE NOTICE 'V001 already applied; skipped';
    ELSE
        EXECUTE $schema_payload$
__BODY__
$schema_payload$;
        INSERT INTO schema_migrations(version, description, checksum)
        VALUES (1, 'Initial collaboration schema', '__CHECKSUM__');
        RAISE NOTICE 'V001 applied';
    END IF;
END
$migration_runner$;
COMMIT;
'@
$migration = $template.Replace('__CHECKSUM__', $checksum).Replace('__BODY__', $body).Replace("`r`n", "`n") + "`n"
$migrationDirectory = Join-Path $postgres 'migrations'
New-Item -ItemType Directory -Force $migrationDirectory, $OutputDirectory | Out-Null
[IO.File]::WriteAllText((Join-Path $migrationDirectory 'V001__initial_schema.sql'), $migration, $utf8)
$runtimeFiles = @()
foreach ($package in @('postgresql', 'redis')) {
    $packageRoot = Join-Path $deploy $package
    # 明确列举交付文件；本地 .env 和数据卷不进入包。
    $items = if ($package -eq 'postgresql') {
        @('sql', 'migrations', 'compose.yaml', 'migrate.ps1', 'README.md', '.env.example')
    } else {
        @('redis.conf', 'start.sh', 'auth-cli.sh', 'compose.yaml', 'start.ps1', 'verify.ps1', 'README.md', '.env.example')
    }
    $paths = @($items | ForEach-Object { Join-Path $packageRoot $_ })
    foreach ($path in $paths) { if (!(Test-Path -LiteralPath $path)) { throw "Missing package file: $path" } }
    foreach ($path in $paths) {
        if (Test-Path -LiteralPath $path -PathType Container) {
            $runtimeFiles += @(Get-ChildItem -LiteralPath $path -Recurse -File | Select-Object -ExpandProperty FullName)
        } else { $runtimeFiles += $path }
    }
    Compress-Archive -Path $paths -DestinationPath (Join-Path $OutputDirectory "$package.zip") -Force
}
$runtimeFiles += @('deploy/compose.yaml', 'deploy/.env.example', 'deploy/.dockerignore',
    'deploy/runtime/Dockerfile', 'deploy/runtime/start.sh', 'deploy/runtime/health.sh',
    'scripts/start-data.ps1', 'scripts/build-data-packages.ps1', 'scripts/verify-data.ps1', 'scripts/verify-data-lifecycle.ps1',
    'scripts/data-integrity.sql', 'docs/data-infrastructure.md') | ForEach-Object { Join-Path $root $_ }
Add-Type -AssemblyName System.IO.Compression.FileSystem
$runtimePath = Join-Path $OutputDirectory 'data-runtime.zip'
$stream = [IO.File]::Open($runtimePath, [IO.FileMode]::Create)
$archive = New-Object IO.Compression.ZipArchive($stream, [IO.Compression.ZipArchiveMode]::Create)
try {
    foreach ($path in $runtimeFiles) {
        $relative = $path.Substring($root.Length + 1).Replace('\', '/')
        [IO.Compression.ZipFileExtensions]::CreateEntryFromFile($archive, $path, $relative) | Out-Null
    }
} finally { $archive.Dispose(); $stream.Dispose() }
$manifest = @('postgresql.zip', 'redis.zip', 'data-runtime.zip') | ForEach-Object {
    $fileHash = Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $OutputDirectory $_)
    $fileHash.Hash.ToLowerInvariant() + '  ' + $_
}
[IO.File]::WriteAllLines((Join-Path $OutputDirectory 'SHA256SUMS.txt'), [string[]]$manifest, $utf8)
Write-Host "Built single migration, component packages and single-container runtime package in $OutputDirectory"
